### ISSUE TITLE
Deploy on heroku

### ISSUE THREAD

**Issue by TaherCCG** [TaherCCG/airybitesrecipes#7]

**Comment by TaherCCG** [comment]
- [ ] Create Requirements.txt #19 
- [ ] Create Procfile #20 
- [ ] Configure Settings in Heroku #21 
- [ ] Link Database URL #22

**Comment by TaherCCG** [comment]
Created requirements.txt
Created Procfile
Configured App Confidentials in Heroku setting

**Comment by TaherCCG** [comment]
Deployment to Heroku Successful!

**Comment by TaherCCG** [comment]
Database URI Linked
